development:
  adapter: postgresql
  database: stats_development
  username: despo
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8

test: &test
  adapter: postgresql
  database: patientlog_test
  username: despo
  password:
  min_messages: WARNING
  host: localhost
  encoding: utf8

cucumber:
  <<: *test
